### ISSUE TITLE
Using env python

### ISSUE THREAD

**Issue by abalakersky** [lucioveloso/lambda-toolkit#1]
Thank you for your work. 
One issue I run into right away is the hardcoded link to `#!/usr/bin/python` in the shebang line of your scripts. This, for example, does not work inside virtualenvironments. 
If you would replace the shebang line with `#!/usr/bin/env python` this will make it work across all different types of environments and setups.

Thank you

**Comment by lucioveloso** [comment]
Hi abalakersky,

Thank you for the suggestion. I fixed it and committed a new version. Please let me know if there are another things that we can improve.
