### ISSUE TITLE
Reuse the same rolename when re-deploy lambda function

### ISSUE THREAD

**Issue by felipeamarante** [lucioveloso/lambda-toolkit#34]
(venv) ☁  iotbtn  lt project deploy -p iotbtn -R us-east-1
Initializing lambda-toolkit CLI (v0.3.1) - Region: eu-west-1 - Auth: file
[CRITICAL] The option '--rolename' is required

**Comment by lucioveloso** [comment]
Hi. Please test the version 0.3.2.

**Comment by felipeamarante** [comment]
All good now!

(venv) ☁  venv  lt project deploy -p iotbtn -R us-east-1
Initializing lambda-toolkit CLI (v0.3.2) - Region: eu-west-1 - Auth: file
[INFO] Updating region to 'us-east-1'.
[DEBUG] Updating project environment to: 'iotbtn'
[INFO] Lambda project iotbtn was redeployed.
